-- CONSTANTS
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("TEST_PENDING","1001", "TEST_RESULT", "Pending", "Pending test", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("TEST_NEGATIVE", "1002","TEST_RESULT", "Negative", "Pending test", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("TEST_POSITIVE", "1003","TEST_RESULT", "Positive", "Pending test", 0);


INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("CLINICAL_EVALUATION","1020","IDENTIFIED_BY", "Clinical evaluation", "Identified by clinical evaluation", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("CONTACT_TRACING","1021","IDENTIFIED_BY", "Contact tracing", "Identified by contact tracing", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("COMMUNITY_SURVEILLANCE","1022","IDENTIFIED_BY", "Community surveillance", "Identified by community surveillance", 0);


INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("PUI_INFO","1040","QUESTIONNIER_CATEGORY", "PUI Information", "Information about Person under investigation", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("SYMPTOMS","1041","QUESTIONNIER_CATEGORY", "Symptoms", "Symptoms", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("EXISTING_CONDITION","1042","QUESTIONNIER_CATEGORY", "Existing condition", "Existing condition", 0);


INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("STABLE","1060","STATUS", "PUI Status stable.", "", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("CRITICAL","1061","STATUS", "PUI Status critical.", "", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("DECEASED","1062","STATUS", "PUI Status deceased.", "", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("RECOVERED","1063","STATUS", "PUI Status recovered.", "", 0);
INSERT INTO CONSTANT_ENUM(ENUM_NAME, ENUM_CODE, ENUM_TYPE, ENUM_LABEL, ENUM_DESC, DISABLED) VALUE("NA","1064","STATUS", "Not available", "", 0);